### PR TITLE
Fix how REPL and LSP handle syntax errors

### LINKED ISSUE #11: Syntax errors in the REPL keep asking for more input
E.g. if you type `foo bar;` and then hit enter, you'll be prompted for more input.

### LINKED ISSUE #66: Comma related issues can freeze the extension
If you start with

```
SELECT 
	1 AS a
;
```

and then transform it to

```
SELECT 
	1 AS a
         2 as b
;
```

the LSP will just hang (if you try to preview the query, for example).

The same thing appears to happen with hanging commas:

```
SELECT 
	1 AS a,
         2 as b,
;
```

### PR DESCRIPTION
**Pull request by ankrgyl**
Fix some bugs related to syntax errors:

In the REPL, we now check for semicolons to know if a statement _really_ has more (Fixes #11).

We rely on` on_schema()` in the LSP to notify the UI of errors and increment the version (so processes waiting on the latest version can proceed). Prior to this change, however, we didn't call `on_schema()` if the parser failed (we also didn't call it from `compile_schema_ast()`, but luckily do not use that in the LSP).

This change reworks `on_schema()` to _always_ be called, so that the LSP can update its bookkeeping state (Fixes #66, #72)

### CODE REVIEW

File: queryscript/src/error.rs [hunk 1]
```diff
@@ -182,10 +182,6 @@ impl<V, E: MultiError> MultiResult<V, E> {
             )),
         }
     }
-
-    pub fn ok<'s>(&'s self) -> &'s V {
```
Comment (ankrgyl) [inline queryscript/src/error.rs:186]: I removed this function because it doesn't actually have `ok()` semantics (i.e. will always return the value, even in the presence of errors)
